### ISSUE TITLE
Issue with big repos

### ISSUE THREAD

**Issue by jorinvo** [caarlos0/starcharts#1]
https://starcharts.herokuapp.com/facebook/react
returned 
```json
failed to get stargazers from github api: {
  "documentation_url": "https://developer.github.com/v3/#abuse-rate-limits",
  "message": "You have triggered an abuse detection mechanism. Please wait a few minutes before you try again."
}
```

Not sure if this is something that can be fixed or if it's just a limit when using the Github API.

**Comment by jorinvo** [comment]
This one too
![screen shot 2017-07-07 at 13 37 34](https://user-images.githubusercontent.com/738978/27956303-80093c70-6319-11e7-911a-e56c8e6b69fa.png)

**Comment by caarlos0** [comment]
http://starcharts.herokuapp.com/rails/rails

**Comment by caarlos0** [comment]
it may still fail when rate limits are hit and the repo is big because heroku cuts requests afters 30s...

**Comment by caarlos0** [comment]
caching by page may also improve that.

**Comment by caarlos0** [comment]
next step is add caching using redis instead of in-memory

**Comment by caarlos0** [comment]
facebook/react would work after a few retries (caching is now done by page)... 

others seems to be working

**Comment by caarlos0** [comment]
```
{"message":"In order to keep the API fast for everyone, pagination is limited for this resource. Check the rel=last link relation in the Link response header to see how far back you can traverse.","documentation_url":"https://developer.github.com/v3/#pagination"}
```

🤷‍♂️

**Comment by jorinvo** [comment]
Cool thanks for the quick fix! I think this is good enough. Can close this for now :)
