### ISSUE TITLE
"rate limited, please try again later"

### ISSUE THREAD

**Issue by aheze** [caarlos0/starcharts#118]
First off, thank you for making this awesome repo! It used to show a nice chart of the stargazers over time. But now it seems that every repo besides [caarlos0/starcharts](https://starchart.cc/caarlos0/starcharts) gets a "rate limited, please try again later" error.

![In Chrome: Rate limited, please try again later](https://user-images.githubusercontent.com/49819455/118222342-4e4e8580-b434-11eb-8b2c-8b952e5f22b0.png)

For example: https://starchart.cc/aheze/SupportDocs

**Comment by caarlos0** [comment]
it can happen, unfortunately... nothing I can do.. eventually it'll cache things and work again

**Comment by aheze** [comment]
No problem! Again, thank you for the awesome repo!

**Comment by caarlos0** [comment]
BTW, if you want you can run one of your own somewhere, only dep (and not mandatory) is redis for caching :)

**Comment by Yiyiyimu** [comment]
Hi @caarlos0 I think a good way to deal with this problem is to add an interface so users could upload their token to fetch the graph (but only for the first time they try to get the graph) like https://github.com/timqian/star-history

**Comment by caarlos0** [comment]
yeah but I don't have time to implement it...
