### ISSUE TITLE
api key donations

### ISSUE THREAD

**Issue by caarlos0** [caarlos0/starcharts#125]
Ok, since rate limit is always hitting, even after the recent efforts using etag and more redis memory for caching... @ahmetb come with an idea of having a pool of api keys.

So, this is issue is where we're going to do so.

The API key needs no permissions, and if you want to help, you can share yours via email at `carlos <at> becker.software`

I'll implement the code to round-robin and mark keys as "bad" in the following days.

We can also come up with some way of saying "thanks" to the key donors either here in the repo or in the website, so if you want your name to show up, please let me know in the email as well.

If you are good with frontends, I really need some help doing a "makeover" of our current frontend as well :) #124

**Comment by ahmetb** [comment]
I've sent the first key! Let's keep this running.

**Comment by ertyurk** [comment]
sent a new one 👍🏼

**Comment by AbdullahAki** [comment]
i sent a key

**Comment by berabulut** [comment]
just send one

**Comment by emresudo** [comment]
One from me too :)

**Comment by DLLWhisperer** [comment]
one from me

**Comment by ebati** [comment]
:+1:

**Comment by anilmisirlioglu** [comment]
one from me 👍🏻

**Comment by ycd** [comment]
Just sent a new 🔑

**Comment by vahdet** [comment]
Have shot an email. Guess I'm num.10 :)

**Comment by caarlos0** [comment]
Thanks everyone!

Should be enough to start... I have metrics so I'll keep an eye and see how it goes.

FWIW, here's the round robin impl: https://github.com/caarlos0/starcharts/pull/126

**Comment by eminks** [comment]
👍

**Comment by caarlos0** [comment]
Hey, as a feedback, we are much more stable now!

<img width="3005" alt="image" src="https://user-images.githubusercontent.com/245435/127694019-52c0b3ba-4835-4503-bb75-8505ae7ad802.png">

and token usage is pretty low after I started failing-fast repos with more than 40k stars (which github does not let scan all pages anyway):

<img width="2999" alt="image" src="https://user-images.githubusercontent.com/245435/127694087-66f39aed-d3fb-47e5-8386-c7a0d171b606.png">

So I think we should be good for now!

If someone wants to help writing a new frontend, let me know and let's work together 🙏

**Comment by caarlos0** [comment]
Ah, and thanks again for everyone that jumped in to help on this 🤘

**Comment by santiesque** [comment]
@caarlos0 I love the project. Gonna put it on github.com/formsend/nano.to repo README. 

I run [nano.to](https://nano.to). If you accept NANO I'd be happy to support, and cover my bandwidth use at the same time.

**Comment by caarlos0** [comment]
hey @santiesque, sure thing, `nano_1itwnh7yena7houij3urpe5besw5za6r37z8hpqjezepsre1k9jk8dhkorn5`

**Comment by santiesque** [comment]
@caarlos0 

Done! $100 coming your way. That should cover my bandwidth for a few months.

Consider reserving a name on [nano.to](nano.to) (w/ NANO). We're launching a 'Open Source Donation Pool' soon.

**Comment by caarlos0** [comment]
Thanks @santiesque 🙏

**Comment by caarlos0** [comment]
I think this can be closed now.

Thanks again everyone!
