### ISSUE TITLE
Feature: Control the coloring of the background and the lines 

### ISSUE THREAD

**Issue by wiseaidev** [caarlos0/starcharts#135]
Hey there, I have just stumbled upon this wonderful project, and I think it would be nice to add support for changing colors using some extra URL parameters. 

```sh
starchart.cc/caarlos0/starcharts.svg?background="dark"&axis="white"&line="blue"
```

**Comment by caarlos0** [comment]
not particularly interested in working on this right now, but might merge it if someone opens a pr.

**Comment by evg4b** [comment]
Hi @caarlos0 , it seems this issue can now be closed as the feature has been implemented.
