### ISSUE TITLE
Support Dark Mode (Transparent SVG)

### ISSUE THREAD

**Issue by nano2dev** [caarlos0/starcharts#146]
Hello, friend. 

I'm [this](https://github.com/caarlos0/starcharts/issues/125#issuecomment-924421977) person.

I love starcharts. Use it lots. I don't have the time to provide a PR, but would love to encourage development of this specific Feature with another donation in Nano :)  

The idea is easy to understand. Happy to provide further context.

Imagine this image, **transparent** and "bright" color graph lines :) 

<img width="1035" alt="Screen Shot 2022-06-27 at 2 46 32 PM" src="https://user-images.githubusercontent.com/9022456/176013534-37407c4e-c84d-4727-80fc-205693213de2.png">
.

@nano2dev on Twitter. 

Cheers.

**Comment by caarlos0** [comment]
if anyone wants to take a swing at this, I'm happy to merge it... don't have time to implement it myself rn

**Comment by evg4b** [comment]
Hi @caarlos0 , it seems this issue can now be closed as the feature has been implemented.
