### ISSUE TITLE
hope compare multiple repository like this.

### ISSUE THREAD

**Issue by zicjin** [caarlos0/starcharts#18]
![image](https://user-images.githubusercontent.com/199482/65808902-607da080-e1ca-11e9-8409-c79533952d6d.png)
https://star-history.t9t.io/#Haneke/HanekeSwift&kean/Nuke&hyperoslo/Cache&onevcat/Kingfisher&Alamofire/AlamofireImage

**Comment by caarlos0** [comment]
the purpose of starcharts is to be used on repo readmes and etc... adding multiple repos will be against that and will for sure break the hit rate limits and all...

that being said, I rather not do this.

Thanks for the suggestion though :)
