### ISSUE TITLE
Chart does not update

### ISSUE THREAD

**Issue by nikitavoloboev** [caarlos0/starcharts#2]
I use your chart in [this repository](https://github.com/nikitavoloboev/learn-anything) but I don't understand how can I update the image of it. I thought it was auto updating. 

Thank you for any help.

**Comment by caarlos0** [comment]
Hi @nikitavoloboev, it seems that github caches it, yeah.

I'll send an email to their support to see how can I solve this.

Thanks for reporting it!

**Comment by caarlos0** [comment]
Hi @nikitavoloboev , I've pushed a fix! Can you try to add something like a `?a=1` or whatever to the url in your readme (just so github update it, you can remove it later) to see if it works now?

**Comment by caarlos0** [comment]
(maybe it is not even needed to append anything to the URL)

**Comment by caarlos0** [comment]
i think its fixed now!

thanks for reporting @nikitavoloboev

**Comment by zicklag** [comment]
So do you have to update the README to update the graph, or is there a way to have it update automatically?

**Comment by caarlos0** [comment]
it auto updates, but github caches it so it may take some time

**Comment by zicklag** [comment]
OK, thanks. I'm fine if it takes a while, as long as it will update eventually.
