### ISSUE TITLE
Incorrect number of stars charted

### ISSUE THREAD

**Issue by ItsNickBarry** [caarlos0/starcharts#44]
The chart displays one fewer star than expected for repositories with more than one star, but fewer than at most 290.
https://starchart.cc/itsnickbarry/fruit-salad
https://starchart.cc/rkalis/truffle-assertions

This seems like an off-by-one problem, but it doesn't appear to affect repositories with 1 star:
https://starchart.cc/itsnickbarry/endless-sky-flamethrower-turret

**Comment by caarlos0** [comment]
the chart library does an approximation and the end result is not always accurate, specially on repos with few starts.

this is working as expected.

thanks for the report though :)
