### ISSUE TITLE
Use multiple github tokens

### ISSUE THREAD

**Issue by x0rzkov** [caarlos0/starcharts#96]
Hi @caarlos0 ,

Hope you are all well !

I was wondering if we could integrate a github client managing multiple personal tokens.
It would be great for handling more repositories.

I found that package managing multiple tokens for saving dev time:
Ref: https://github.com/fengyfei/nuts/blob/master/github/client/client.go

Thanks for any insights or inputs on that.

Cheers,
X

**Comment by caarlos0** [comment]
still need to have multiple users for that to work though...

**Comment by caarlos0** [comment]
improved a bit on https://github.com/caarlos0/starcharts/pull/121

**Comment by caarlos0** [comment]
this is implemented and in production for a while now.
